### ISSUE TITLE
Version bump request

### ISSUE THREAD

**Issue by mz1193** [rlac/flatpak-alephone#1]
Hi there, thanks for packaging this for Flatpak!

Any chance of a version bump in the future? The upstream project recently released version 1.4

**Comment by rlac** [comment]
I've pushed an update with 1.4. Let me know if you have any issues.

**Comment by mz1193** [comment]
> I've pushed an update with 1.4. Let me know if you have any issues.

Seems to build and work perfectly! Played a little bit of each so far. Thank you for the update. :)
